### ISSUE TITLE
关于此mod在服务器报错的问题

### ISSUE THREAD

**Issue by Ristorff** [TeamMoegMC/Frosted-Heart#1]
服务器安装此mod后会无法启动，并有如下错误报告：

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.0.jar:36.2] {}
-- MOD frostedheart --
Details:
	Mod File: frostedheart-1.16.5-0.2.0.jar
	Failure message: Frosted Heart (frostedheart) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
	Mod Version: 1.16.5-0.2.0
	Mod Issue URL: https://github.com/TeamMoegMC/Frosted-Heart/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201] {}
	at com.teammoeg.frostedheart.block.FHStoneMultiblockBlock.<init>(FHStoneMultiblockBlock.java:45) ~[frostedheart:1.16.5-0.2.0] {re:classloading}
	at com.teammoeg.frostedheart.block.GeneratorMultiblockBlock.<init>(GeneratorMultiblockBlock.java:35) ~[frostedheart:1.16.5-0.2.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.teammoeg.frostedheart.content.FHContent.populate(FHContent.java:70) ~[frostedheart:1.16.5-0.2.0] {re:classloading}
	at com.teammoeg.frostedheart.FHMain.<init>(FHMain.java:78) ~[frostedheart:1.16.5-0.2.0] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_201] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_201] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_201] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_201] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_201] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_201] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_201] {}

请问要在服务器添加此mod的话需要如何解决。

**Comment by yuesha-yc** [comment]
升级到最新版

**Comment by yuesha-yc** [comment]
Closes by 0.3.0
